### PR TITLE
Fix graphql issue after upgrade to 1.13.0

### PR DESCRIPTION
**Pull request by stejskalleos**
For https://github.com/theforeman/foreman/commit/952e1614db88de4120a60cb0da5da53c0304dfc5

### CODE REVIEW

**Comment by stejskalleos** [comment]
@ofedoren @evgeni 

I fixed issue with loading foreman + foreman_ansible but there is problem with tests:
```
 Failed to implement Host.allAnsibleRoles, tried:

            - `Types::Host#all_ansible_roles`, which did not exist
            - `Host::Managed#present_all_ansible_roles`, which did not exist
            - Looking up hash key `:present_all_ansible_roles` or `"present_all_ansible_roles"` on `host40`, but it wasn't a Hash

            To implement this field, define one of the methods above (and check for typos)
```
Any help would be appreciated, I don't have much experience with graphql and don't understand much the internals of it.

**Comment by evgeni** [comment]
I pushed one permission change, but that doesn't fix the `all_ansible_roles` one, will look into that probably next week

**Comment by ofedoren** [comment]
Hmm... I don't get it, locally `rake test:foreman_ansible TEST=test/graphql/**/*_test.rb` passes...

**Comment by stejskalleos** [comment]
> Hmm... I don't get it, locally `rake test:foreman_ansible TEST=test/graphql/**/*_test.rb` passes...

Really, for me it's failing same way as in CI

**Comment by ekohl** [comment]
Unrelated to this PR, but first of all: the paths are very confusing since this is actually in Foreman, not `foreman_ansible`.
```
/home/runner/work/foreman_ansible/foreman_ansible/app/models/concerns/host_mix.rb:10: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/runner/work/foreman_ansible/foreman_ansible/app/models/concerns/has_many_common.rb:73: warning: The called method `belongs_to' is defined here
```

I already found these in my Rails 7 & Ruby 3.1 PR but now submitted it separately: https://github.com/theforeman/foreman/pull/9441

**Comment by ekohl** [comment]
And for the other bit I opened https://github.com/theforeman/foreman_ansible/pull/564

**Comment by evgeni** [comment]
Yeah, I am kinda sure it's needed. I just don't understand why it fails on CI

**Comment by ofedoren** [comment]
@evgeni, :green_apple: x) It just needed to be scared of verbosity...

**Comment by evgeni** [comment]
Yeah, idk. I pushed one version w/o `--trace -v` and it failed… *shakes fist*

**Review by ofedoren — APPROVED** [review]

**Review by evgeni — APPROVED** [review]

**Comment by stejskalleos** [comment]
:green_apple: Tested locally & tests passed, so let's get this in.

Thanks @evgeni @ofedoren !

**Pull request merged**
