### PR TITLE
Fixes #18150 - Ansible roles run after a host is provisioned

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by Gerrit91** [comment]
@dLobatog Some things are not working for me with these changes. 

Firstly, when verbosity_level is set to 0, the return value of setup_verbosity is nil. The command that's going to executed results in

```
Running command [{"JSON_INVENTORY_FILE"=>"/tmp/.../foreman-inventories/..."}, "ansible-playbook", "-i", "/root/foreman_ansible/bin/json_inventory.sh", nil, "/tmp/.../foreman-playbook-....yml"]
```

Throwing an error in dynflow:

```
[foreman-tasks/dynflow] [E] error while dispatching request to runner ...:TypeError no implicit conversion of nil into String:
```

A possible fix is contained in #69.

Secondly, the playbooks cannot be found any longer. The tests succeed of course, but looking at the UI reveals: "StandardError: Script execution failed" due to the error with Ansible "ERROR! the playbook:  could not be found".

**Comment by Gerrit91** [comment]
The second problem was happening due to my implementation in #69. Actually, the verbosity should not be inserted into the command array at all if the level is smaller than 1.

**Comment by Gerrit91** [comment]
By the way, I really like how you solved that problem with the proxy solution! 

The only thing that I think is a little odd, is that in the task UI it says `Play Ansible roles on host <host_name> through not_defined` even though we now that Ansible is running on the localhost, which is **defined**. If there was no proxy found, I think it should just state `Play Ansible roles on host <host_name>`.

**Comment by Gerrit91** [comment]
By the way and just for your personal information (yes, I heard your sprint review ☺️), theoretically it's possible to have an arbitrarily high verbosity level in modules, so -vvvv is not the maximum verbosity. It's also briefly mentioned [in this video](https://www.youtube.com/watch?v=YqaTx1s8i6k#t=17m19s).

**Comment by iNecas** [comment]
Ad verbosity level: I've filed the issue for this, just for make it easier for others to find the reason of the problem, before we have a fix http://projects.theforeman.org/issues/18278

**Pull request merged**
