### PR TITLE
Fixes #33817 - Add pagination to previous jobs

### PR DESCRIPTION
**Pull request by xprazak2**
Needs https://github.com/theforeman/foreman_ansible/pull/473, therefore wip

### CODE REVIEW

**Comment by xprazak2** [comment]
No longer wip.

**Review by amirfefer — COMMENTED** [review]
Can't test it, while trying to add a scheduled job it resulted in error:
```
There was a following error when creating Ansible job: Error: JobInvocationInput isn't a defined input type (on $jobInvocation) Field 'createJobInvocation' doesn't exist on type 'Mutation' Variable $jobInvocation is declared by CreateJobInvocation but not used
```

**Comment by xprazak2** [comment]
Seems like the server cannot find the [mutation definition](https://github.com/theforeman/foreman_remote_execution/commit/7c04fb650109ad8ff7d1071ae79b5a0f82cc39fb). Does updating remote execution help?

**Review by ezr-ondrej — APPROVED** [review]
Thanks @xprazak2 ! :+1:

**Pull request merged**
