### PR TITLE
Fixes #35628 - Keep logs from failed Github actions

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Having logs could help here. This is what we do in rex https://github.com/theforeman/foreman_remote_execution/pull/610

**Comment by stejskalleos** [comment]
> Having logs could help here. This is what we do in rex https://github.com/theforeman/foreman_remote_execution/pull/610

Nice, that'll be useful!

**Comment by adamruzicka** [comment]
Would be nice if the tests actually failed now so we could see whether it really works

**Review by adamruzicka — APPROVED** [review]
I couldn't see it in action, but we have the exact same thing in REX and there it works well. We can always go back and fix it in case there are any issues with it

**Comment by adamruzicka** [comment]
Thank you @stejskalleos !

**Pull request merged**
