### PR TITLE
Fixes #28463 - Fix missing roles in the assigned roles list

### PR DESCRIPTION
**Pull request by amasolov**
Needed to populate directlyAssignedRoles with allAssignedRoles instead of assignedRoles to get the whole list of roles not just visible ones.

### CODE REVIEW

**Comment by amasolov** [comment]
Fixed my own mess with commits. Should be fine now.

**Comment by amasolov** [comment]
Looks like this PR also fixes [#27678](https://projects.theforeman.org/issues/27678). Can't reproduce the described problem after applying this change.

**Comment by xprazak2** [comment]
Good catch. You need to [pass](https://github.com/theforeman/foreman_ansible/blob/master/webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcher.js#L90) `allAssignedRoles` as a prop to the `AssignedRolesList` to propagate it from a parent component though:

```js
<AssignedRolesList
  allAssignedRoles={allAssignedRoles}
//other props
/>
```

**Comment by amasolov** [comment]
> You need to [pass](https://github.com/theforeman/foreman_ansible/blob/master/webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcher.js#L90) `allAssignedRoles` as a prop to the `AssignedRolesList`

Yup, somehow missed that in my commit.

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
