### PR TITLE
Allow REX 9.0

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by nofaralfasi** [comment]
LGTM, can we merge it? @Ron-Lavi

**Comment by nofaralfasi** [comment]
Thanks @evgeni!

**Comment by evgeni** [comment]
@nofaralfasi @ares could we get a release with this fix in? Otherwise nightly is broken right now

**Comment by Ron-Lavi** [comment]
@evgeni sure, I can release tomorrow morning

**Pull request merged**
