### PR TITLE
Fixes #36473 - Add missing ouia-ids

### PR DESCRIPTION
**Pull request by MariaAga**
More about why we need them here: https://www.patternfly.org/v4/developer-resources/open-ui-automation

### CODE REVIEW

**Comment by adamruzicka** [comment]
LGTM, but there's a conflict

**Comment by MariaAga** [comment]
Thanks, fixed the conflict

**Review by adamruzicka — COMMENTED** [review]
LGTM

@stejskalleos any idea about the test failures? JS-only changes surely cannot make the ruby tests fail, right?

**Comment by stejskalleos** [comment]
I re-rerun the tests, it's the issue I talked about, for some reason tests are failing on fresh DB,
something with Dynflow, not sure what.

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**

**Comment by stejskalleos** [comment]
thanks everyone

**Pull request merged**
