### PR TITLE
Refs #34713 - Replace pf3 OverlayTrigger

### PR DESCRIPTION
**Pull request by MariaAga**

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Can we have a separate Redmine ticket for this and link it to the original one?

**Comment by MariaAga** [comment]
Yeah added a redmine, and renamed `margin-right` to `marginRight`

**Review by stejskalleos — CHANGES_REQUESTED** [review]
:heavy_check_mark: LGTM, tested the code and it works very well.

The only thing is the commit message, @MariaAga could you please update the commit message as `Fixes #000 - message`?

After that PR will be ready to go!

**Comment by stejskalleos** [comment]
Thanks @MariaAga !

**Pull request merged**
