### PR TITLE
Refs #36021 - disable Ansible actions if hostgroup is empty

### PR DESCRIPTION
**Pull request by nofaralfasi**
Disable Ansible actions links for hostgroups with no roles or hosts

### CODE REVIEW

**Review by stejskalleos — COMMENTED** [review]
I can't test it, roles switcher doesn't work on host group page

hg_roles

**Comment by nofaralfasi** [comment]
> I can't test it, roles switcher doesn't work on host group page

That's weird... It's working for me. And I don't see how my changes could affect that.
Could you tell me if it's working on master branch?

**Comment by stejskalleos** [comment]
Huh, this is my setup:
Foreman on latest `develop`, foreman_ansible on latest `master`
1. Foreman with few plugins
2. Foreman with foreman_ansible only (and it's dependencies)

Both have same error. Even when I do total cleanup of `node_modules` with
```
rm -rf node_modules package-json.lock tmp/*;npm cache clean --force;npm install
```
or when I have clean browser cache, I still have the problem. Here's the error:
```
react-dom.development.js:88 Warning: React does not recognize the `viewType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `viewtype` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Pagination)
    in Pagination (created by Pagination)
    in Pagination (created by AvailableRolesList)
    in div (created by AvailableRolesList)
    in div (created by ListView)
    in ListView (created by AvailableRolesList)
    in AvailableRolesList (created by AnsibleRolesSwitcher)
    in div (created by Col)
    in Col (created by AnsibleRolesSwitcher)
    in div (created by Row)
    in Row (created by AnsibleRolesSwitcher)
    in div (created by Grid)
    in Grid (created by AnsibleRolesSwitcher)
    in AnsibleRolesSwitcher (created by ConnectFunction)
    in ConnectFunction
    in Unknown (created by I18nProviderWrapper(Component))
    in IntlProvider (created by I18nProviderWrapper(Component))
    in I18nProviderWrapper(Component) (created by StoreProvider(I18nProviderWrapper(Component)))
    in Provider (created by StoreProvider(I18nProviderWrapper(Component)))
    in StoreProvider(I18nProviderWrapper(Component)) (created by DataProvider(StoreProvider(I18nProviderWrapper(Component))))
    in DataProvider(StoreProvider(I18nProviderWrapper(Component)))

react-dom.development.js:88 Warning: React does not recognize the `dropdownButtonId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dropdownbuttonid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Pagination)
    in Pagination (created by Pagination)
    in Pagination (created by AvailableRolesList)
    in div (created by AvailableRolesList)
    in div (created by ListView)
    in ListView (created by AvailableRolesList)
    in AvailableRolesList (created by AnsibleRolesSwitcher)
    in div (created by Col)
    in Col (created by AnsibleRolesSwitcher)
    in div (created by Row)
    in Row (created by AnsibleRolesSwitcher)
    in div (created by Grid)
    in Grid (created by AnsibleRolesSwitcher)
    in AnsibleRolesSwitcher (created by ConnectFunction)
    in ConnectFunction
    in Unknown (created by I18nProviderWrapper(Component))
    in IntlProvider (created by I18nProviderWrapper(Component))
    in I18nProviderWrapper(Component) (created by StoreProvider(I18nProviderWrapper(Component)))
    in Provider (created by StoreProvider(I18nProviderWrapper(Component)))
    in StoreProvider(I18nProviderWrapper(Component)) (created by Dat
```

@Ron-Lavi @MariaAga Pinging our JS devs, any idea where could be the problem?

**Comment by MariaAga** [comment]
This is a warning that is caused by ansible not setting the pagination correctly and unrelated to this pr. Im guessing https://github.com/theforeman/foreman_ansible/pull/556/files should also fix that if its ever revived

**Review by Ron-Lavi — APPROVED** [review]
Thanks @nofaralfasi ! LGTM

tested and it works well with Foreman develop:
Screenshot - 2023-03-12T151734 850

Since this requires also a Cherry Pick, I checked with v10 and it seems that `configure Ansible Jobs` button doesn't get disabled.
Screenshot - 2023-03-12T151831 213

**Comment by nofaralfasi** [comment]
Thanks @Ron-Lavi!
BTW, should I be worried about your first screenshot? (I'm talking about the `>>` `<<`)

I'll take care of the CP :)

**Comment by Ron-Lavi** [comment]
Ahah It's just showing the strings that are marked for translation :)
Merging

**Comment by nofaralfasi** [comment]
> Since this requires also a Cherry Pick, I checked with v10 and it seems that `configure Ansible Jobs` button doesn't get disabled.
That's interesting. I don't see that behavior when checking v10. Maybe you didn't restart the server after applying these changes?

**Comment by Ron-Lavi** [comment]
double-checked and CP for v10 works properly for me now 👍🏼 
opened CP: https://github.com/theforeman/foreman_ansible/pull/613

**Pull request merged**
