### PR TITLE
Refs #33142 - add missing permissions

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Additionally to #433 we need to add permissions for the parent controller.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
@tbrisker, @xprazak2 could one of you? :)

**Review by tbrisker — COMMENTED** [review]
Would this give users with ansible permissions the ability to see other types of lookup values such as puppet?

**Comment by ezr-ondrej** [comment]
> Would this give users with ansible permissions the ability to see other types of lookup values such as puppet?

It should not if they have the permissions set correctly :shrug:
It will, if they use the ancestor controller permissions.

**Comment by tbrisker** [comment]
> It should not if they have the permissions set correctly :shrug:
> It will, if they use the ancestor controller permissions.

I'm not sure I follow? what do you mean if they have the permissions set correctly? 
isn't `/lookup_values` the path used by the puppet class parameters page, and ansible uses `/ansible_override_values`?

**Comment by ezr-ondrej** [comment]
> isn't `/lookup_values` the path used by the puppet class parameters page, and ansible uses `/ansible_override_values`?

no, `lookup _values` is not a core route, the controller is in core usable by any plugin, that choses to use override and both ansible and does that. Not sure if it's the right strategy, because then we can't set the permissions for scoped `LookupValue`, but that's the way it works now, so the permissions should be set that way.

I'm not sure it is a big issue tho

**Review by tbrisker — APPROVED** [review]
Thanks @ezr-ondrej ! I agree it is odd but looks like it works.

**Pull request merged**
