### PR TITLE
[Rubocop] Allow both Hash styles

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Comment by xprazak2** [comment]
Rebase should take care of the test failures.

**Comment by ezr-ondrej** [comment]
The errors are still present, this is hardly cause of them though, right?

**Comment by xprazak2** [comment]
[test foreman_ansible]

**Comment by xprazak2** [comment]
There were test failures because report scanner did not implement the required methods, which was fixed by rebase. Now jenkins fails to configure database. Let's do a re-run, hopefully it will turn green.

**Comment by ezr-ondrej** [comment]
[test foreman_ansible] lets try again :)

**Comment by xprazak2** [comment]
All green now, should this be attached to issue [#30398](https://projects.theforeman.org/issues/30398)? The issue is about DSL docs...

**Comment by ezr-ondrej** [comment]
> All green now, should this be attached to issue [#30398](https://projects.theforeman.org/issues/30398)? The issue is about DSL docs...

It should not, I've stole the ID from the other rubocop PR...
@adamruzicka would that be ok to squash merge and remove the RM id while at it?

**Comment by adamruzicka** [comment]
It is done, thank you @ezr-ondrej & @xprazak2 !

**Pull request merged**
