### PR TITLE
Fixes #25531 - Fetch endpoint uses proxy

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by xprazak2** [comment]
LGTM, will need rebase once https://github.com/theforeman/foreman_ansible/pull/227 is merged for rubocop to pass.

**Comment by ares** [comment]
@ofedoren please rebase when you have a chance

**Comment by ofedoren** [comment]
@ares, rebased. Although there are no test failures, still there are some rubocop offenses. Should I fix them as well?

**Comment by xprazak2** [comment]
I opened https://github.com/theforeman/foreman_ansible/pull/230 to fix the last rubocop offence.

**Comment by xprazak2** [comment]
@ofedoren, could you please rebase on top of latest master to see if rubocop offences are finally gone?

**Comment by ares** [comment]
Thanks @ofedoren, merging!

**Pull request merged**
