### PR TITLE
Fixes #29062 - use new ImporterRegistry to register ForemanAnsible

### PR DESCRIPTION
**Pull request by rahulbajaj0509**

### CODE REVIEW

**Comment by xprazak2** [comment]
I think the test failures are related. I do not see `:fact_registry` defined for `Foreman::Plugin` am I missing a related PR?

**Comment by ares** [comment]
I think it's https://github.com/theforeman/foreman/pull/5010 which is not merged yet in core and is WoC. @rahulbajaj0509 it may be a good idea to link that PR in every plugin you opened these PRs, thanks.

**Comment by rahulbajaj0509** [comment]
@xprazak2  @ares  yes, perfect. I will also update redmine with the related issues. I had to leave at the day but had this in mind :) thanks for looking out for the PR :+1:

**Comment by xprazak2** [comment]
[test foreman_ansible]

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
