### PR TITLE
Fixes #22860 - Extract the most recent strings from the ansible plugin

### PR DESCRIPTION
**Pull request by bkearney**

### CODE REVIEW

**Comment by bkearney** [comment]
@akofink @dLobatog bump on this?

**Comment by akofink** [comment]
I approved, but I don't have write access here, sorry.

**Comment by ares** [comment]
Looks reasonable to me too, I think @bastilian and @dLobatog only have permissions to merge here.

**Comment by bastilian** [comment]
Thank you @bkearney! And @akofink!

**Pull request merged**
