### PR TITLE
Fixes #31980 - Ansible can submit ConfigReport's too

### PR DESCRIPTION
**Pull request by domq**
Same as https://github.com/theforeman/foreman/pull/8361 after I learned about Ruby mixins.

### CODE REVIEW

**Comment by domq** [comment]
[Link to the Redmine bug report #31980](https://projects.theforeman.org/issues/31980)

**Comment by ezr-ondrej** [comment]
ok to test

**Review by ezr-ondrej — APPROVED** [review]
Thanks @domq, great addition! :)

**Comment by ezr-ondrej** [comment]
Test failures are only about bad configuration of rubocop on Jenkins, tests are passing.
Although it would be nice to have a test for this, I'll add it in followup PR.

**Pull request merged**
