### PR TITLE
Update .rubocop_todo.yml

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
[test foreman_ansible]

**Comment by ares** [comment]
now the failures seems to be consistent, but hardly caused by rubocop... could you pretty please take a look at the failing test too? otherwise master job would become red and PRs wouldn't be tested

```
Expected nil to not be empty. (Minitest::Assertion)
/var/lib/workspace/workspace/foreman_ansible-pull-request/database/postgresql/label/fast/ruby/2.4/plugin/test/functional/api/v2/ansible_roles_controller_test.rb:53    
```

**Comment by ofedoren** [comment]
Does this https://github.com/theforeman/foreman_ansible/pull/226 solves that test failures?

If it does, I'll rebase it against this PR, so this can be merged.

**Comment by ares** [comment]
Ok, makes sense. Merging now! Thanks @xprazak2

**Pull request merged**
