### PR TITLE
Fixes #25779 - complete variables API

### PR DESCRIPTION
**Pull request by ares**
This fixes few bugs in existing API and introduces matcher management support. Best tested with related hammer PR that I'll link in a moment

### CODE REVIEW

**Comment by xprazak2** [comment]
Looking good overall.

When creating override, I get an error, but override is created:
```
[vagrant@foreman-devel ~/projects/hammer-cli-foreman-ansible]$curl -H "Accept: application/json" -H "Content-Type: application/json" -k -X POST -u admin:changeme https://foreman-devel.example.com/ansible/api/v2/ansible_override_values -d '{"override_value": { "value": "bla", "match": "domain=example.com"}, "ansible_variable_id": "868" }'| json_reformat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   151    0    52  100    99    181    345 --:--:-- --:--:-- --:--:--   346
{
    "error": {
        "message": "Couldn't find resource"
    }
}

```

When deleting override that does not exists, I get undefined method in controller:

```
NoMethodError: undefined method `destroy' for nil:NilClass
 | /home/vagrant/projects/foreman_ansible/app/controllers/api/v2/ansible_override_values_controller.rb:39:in `destroy'
```

It would be good to have at least some basic tests.

**Comment by ares** [comment]
Thanks I missed this because I tested only through hammer. I now fixed both actions, please take another look.

**Comment by ares** [comment]
[test foreman_ansible]

**Comment by xprazak2** [comment]
Works for me.

**Comment by ares** [comment]
Test failures unrelated, merging. Thanks @xprazak2 for taking a look.

**Pull request merged**
