### PR TITLE
Fixes #36413 - Make PUT /host(group)s/add_ansible_role follow REST specs

### PR DESCRIPTION
**Pull request by ofedoren**
I guess it should be CPed into 11.2.2 :/

### CODE REVIEW

**Comment by nofaralfasi** [comment]
@stejskalleos can we merge this? The failing tests don't seem to be related.

**Comment by stejskalleos** [comment]
@ofedoren can you try rebasing the PR, latest tx changes could fix the failing pipeline.

**Comment by ofedoren** [comment]
Rebased :crossed_fingers:

**Comment by nofaralfasi** [comment]
Thanks! @ofedoren

**Pull request merged**
