### PR TITLE
Don't run ruby tests on push to master

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by nofaralfasi** [comment]
Hi @Ron-Lavi, do you know if we need to run tests when things are merged to the master branch?

**Review by Ron-Lavi — APPROVED** [review]

**Comment by ekohl** [comment]
> do you know if we need to run tests when things are merged to the master branch?

This creates caches which can be reused. It greatly speeds up PR testing between multiple users.

The background is that PR testing creates a cache that can **only** be used by the user who submitted the PR. If you also run it on test it creates a shared cache that's used for everyone.

I'd suggest to revert this change.

**Comment by nofaralfasi** [comment]
>  If you also run it on test it creates a shared cache that's used for everyone.

What do you mean by that? Maybe you meant to say that if you also run the tests on **master** it creates a shared cache...
And thanks for the explanation @ekohl!

**Comment by ekohl** [comment]
Yes, that is exactly what I intended.

For what it's worth, back in March I tried to unify all actions in reusable ones so most plugin authors don't need to think about it anymore. https://github.com/theforeman/actions is the repo and https://github.com/theforeman/actions/issues/1 has a list of TODO items.

https://github.com/theforeman/foreman_ansible/pull/519 needs a rebase after this PR, but that is how I think we should manage testing using GitHub Actions.

**Pull request merged**
