### PR TITLE
Fixes #30483 - Give Foreman operation jobs their own Job Category

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Tests are currently red, but should be fixed by https://github.com/theforeman/foreman_ansible/pull/352 once it gets in

**Comment by adamruzicka** [comment]
Could you please rebase?

**Comment by stejskalleos** [comment]
> Could you please rebase?

Rebased & green!

**Comment by adamruzicka** [comment]
Thank you @stejskalleos !

**Pull request merged**
