### PR TITLE
Fixes #30518 - Remove working directory

### PR DESCRIPTION
**Pull request by patilsuraj767**
Removing the working directory once the job is executed.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
ok to test

**Comment by adamruzicka** [comment]
[test foreman_ansible]

**Comment by tbrisker** [comment]
I thinks the test failures should be fixed by https://github.com/theforeman/foreman_ansible/pull/261/, please try rebasing it on latest master

**Comment by tbrisker** [comment]
test failures are fixed by https://github.com/theforeman/foreman_ansible/pull/360, should be safe to merge now (i didn't test or review though)

**Review by ezr-ondrej — APPROVED** [review]
Thanks @patilsuraj767 !

**Pull request merged**
