### PR TITLE
Fixes #33529 - Add pagination to roles on host detail

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
@amirfefer, any additional concerns?

**Review by amirfefer — DISMISSED** [review]
Thanks @xprazak2 
some  related lint issues, though tests failures seem unrelated
It works as expected 👍

**Comment by xprazak2** [comment]
Rebased and tests are green now.

**Review by ezr-ondrej — APPROVED** [review]
Works and the tests are :green_apple:
Thanks @xprazak2 ! :+1:

**Comment by ezr-ondrej** [comment]
Thanks for the reviews @amirfefer !! :)

**Pull request merged**
