### PR TITLE
Fixes #24262 - cache insights playbook

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
needs https://github.com/theforeman/foreman_remote_execution/pull/374

**Comment by ares** [comment]
REX PR got in

**Comment by ares** [comment]
this will need to be rebased on top of #204 in order to fix rubocop issues

**Comment by bastilian** [comment]
@ares #204 is now merged!

**Comment by ares** [comment]
[test foreman_ansible] I'm on phone, there's a chance plugin jobs apply patches to master, so let's rerun. If it doesn't help, I'll rebase in few hours.

**Comment by ares** [comment]
Rebased, let's see, fingers crossed

**Comment by ares** [comment]
it's green except for mysql that got aborted, I'd say good to go :-)

```
E, [2018-09-12T20:17:51.738794 #4742] ERROR -- /client-dispatcher: Could not find an executor for Dynflow::Dispatcher::Envelope[request_id: 17, sender_id: 9154caa6-3a42-4bc6-9e0c-1dcc922eab49, receiver_id: Dynflow::Dispatcher::UnknownWorld, message: Dynflow::Dispatcher::Event[execution_plan_id: dfbe8ebf-4e10-407c-bdd5-df508b4e8618, step_id: 2, event: Actions::Middleware::WatchDelegatedProxySubTasks::CheckOnProxyActions]] (Dynflow::Error)
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/dynflow-1.1.0/lib/dynflow/dispatcher/client_dispatcher.rb:146:in `dispatch_request'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/dynflow-1.1.0/lib/dynflow/dispatcher/client_dispatcher.rb:117:in `block (2 levels) in publish_request'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/dynflow-1.1.0/lib/dynflow/dispatcher/client_dispatcher.rb:204:in `track_request'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/dynflow-1.1.0/lib/dynflow/dispatcher/client_dispatcher.rb:116:in `block in publish_request'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/dynflow-1.1.0/lib/dynflow/dispatcher/client_dispatcher.rb:245:in `with_ping_request_caching'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/dynflow-1.1.0/lib/dynflow/dispatcher/client_dispatcher.rb:115:in `publish_request'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/dynflow-1.1.0/lib/dynflow/actor.rb:6:in `on_message'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/context.rb:46:in `on_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/executes_context.rb:7:in `on_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/dynflow-1.1.0/lib/dynflow/actor.rb:26:in `on_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/awaits.rb:15:in `on_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/sets_results.rb:14:in `on_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/buffer.rb:38:in `process_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/buffer.rb:31:in `process_envelopes?'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/buffer.rb:20:in `on_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/termination.rb:55:in `on_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/removes_child.rb:10:in `on_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/sets_results.rb:14:in `on_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/core.rb:161:in `process_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/core.rb:95:in `block in on_envelope'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/core.rb:118:in `block (2 levels) in schedule_execution'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/core.rb:115:in `block in schedule_execution'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/serialized_execution.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/serialized_execution.rb:96:in `work'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/serialized_execution.rb:77:in `block in call_job'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
rake aborted!
SignalException: SIGTERM
```

**Comment by bastilian** [comment]
Thank you @ares! It's now merged. :)

**Pull request merged**
