### PR TITLE
Fixes #30972 - use new mounter for ReportJsonViewer component

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Switch to the new `react_component` React mounter for mounting ReportJsonViewer.

### CODE REVIEW

**Comment by xprazak2** [comment]
[test foreman_ansible]

**Comment by xprazak2** [comment]
Works nicely, tests just failed to run.

**Comment by ezr-ondrej** [comment]
Can we get this in now? :thinking:

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
