### PR TITLE
Fixes #29034 - Update Ansible API docs for inventories

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by xprazak2** [comment]
The newly generated routes in doc still cannot be found, this will require a small tweak by having:

```rb
ApiConstraints.new(:version => 2, :default => true)
```

in [routes](https://github.com/theforeman/foreman_ansible/blob/master/config/routes.rb#L75)

**Comment by ofedoren** [comment]
@xprazak2, updated.

**Comment by xprazak2** [comment]
https://github.com/theforeman/foreman_ansible/pull/329 should fix the tests

**Comment by xprazak2** [comment]
@ofedoren, could you rebase on latest master please?

**Comment by ofedoren** [comment]
@xprazak2, thanks. Done :)

**Comment by ofedoren** [comment]
[test foreman_ansible]

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
