### PR TITLE
Adapt to new version of rubocop

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by bastilian** [comment]
Rubocop still seems to have issues with the other `refute(_...)` assertions in tests. :/

**Comment by ekohl** [comment]
This needs a rebase now

**Comment by ares** [comment]
now rubocop fails because of remote execution tests that don't have the same rubocop configuration :-/ not sure what to do about that

**Comment by ares** [comment]
[test foreman_ansible]

**Comment by ares** [comment]
resolved by other PR

**Pull request closed without merging**
