### PR TITLE
[WIP] Fixes #15856 - Play ansible roles through smart proxy

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by dLobatog** [comment]
@adamruzicka  @tstrachota 's PR to include Roles in Host groups was merged just yesterday, mind to rebase?

**Comment by adamruzicka** [comment]
I'm on vacation right now, I'll rebase it when I return

**Comment by dLobatog** [comment]
@adamruzicka Enjoy it!

**Comment by adamruzicka** [comment]
Closing in favor of https://github.com/theforeman/foreman_ansible/pull/40

**Pull request closed without merging**
