### PR TITLE
Fixes #35885 - Error printing report with multiple results

### PR DESCRIPTION
**Pull request by hao-yu**
If Ansible job reported more than one results per action then the config report page will fail to render. For example, a task uses the Ansible copy module to copy multiple files in a loop.

### CODE REVIEW

**Comment by pmoravec** [comment]
Works well when copying either one or multiple files, showing the `msg_json` as example:

2 copy files:

~~~
msg_json={"changed"=>true, "failed"=>false, "module"=>"copy", "msg"=>"All items completed", "results"=>[{"_ansible_item_label"=>"id_rsa_foreman_proxy.pub", "_ansible_no_log"=>nil, "ansible_loop_var"=>"item", "changed"=>true, "diff"=>[], "failed"=>false, "invocation"=>{"dest"=>"/root/.ssh", "group"=>"root", "mode"=>256, "module_args"=>{"dest"=>"/root/.ssh", "group"=>"root", "mode"=>256, "owner"=>"root", "src"=>"/var/lib/foreman-proxy/ssh/id_rsa_foreman_proxy.pub"}, "owner"=>"root", "src"=>"/var/lib/foreman-proxy/ssh/id_rsa_foreman_proxy.pub"}, "item"=>"id_rsa_foreman_proxy.pub"}]}
~~~

1 copy file:

~~~
msg_json={"_ansible_no_log"=>nil, "changed"=>true, "diff"=>[], "failed"=>false, "invocation"=>{"dest"=>"/root/.ssh", "group"=>"root", "mode"=>256, "module_args"=>{"dest"=>"/root/.ssh", "group"=>"root", "mode"=>256, "owner"=>"root", "src"=>"/var/lib/foreman-proxy/ssh/id_rsa_foreman_proxy.pub"}, "owner"=>"root", "src"=>"/var/lib/foreman-proxy/ssh/id_rsa_foreman_proxy.pub"}, "module"=>"copy"}
~~~

I havent checked other modules, though, just the `copy`.

**Comment by evgeni** [comment]
can you add a test like the ones in https://github.com/theforeman/foreman_ansible/pull/580 and https://github.com/theforeman/foreman_ansible/pull/577

**Comment by hao-yu** [comment]
@evgeni Done the test.

**Comment by nofaralfasi** [comment]
Hi @hao-yu, can you please resolve the conflicts and rebase this PR so I can review it? 
Thanks :)

**Comment by Ron-Lavi** [comment]
Hey @nofaralfasi, I rebased for @hao-yu :)

**Comment by nofaralfasi** [comment]
Thanks @Ron-Lavi @hao-yu!

**Pull request merged**
