### PR TITLE
Fixes #17700 - Allow to configure connection type and winrm cert validation via host variables

### PR DESCRIPTION
**Pull request by chilicat**
Allow to configure connection type and winrm cert validation via host variables

### CODE REVIEW

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@chilicat For the connection type and the windows settings, it looks like you're missing the Setting part. Please take a look at https://github.com/theforeman/foreman_ansible/commit/a818cfbd220840fc63221a39353dbed35196b3d2#diff-da709483ecb0994a5ecdf04494885c48 for an example on how to do it. You'd have to add a few lines to `app/models/setting/ansible.rb` I think. Thanks @chilicat !

**Comment by chilicat** [comment]
codeclimate fails now with a lot of errors not related to my change.

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
Thanks @chilicat 😄 !

**Comment by chilicat** [comment]
Thanks for merging. 
This is maybe something for the dev mailing list but do you have any thoughts about how to handle passwords and maybe ssh keys in the future?

**Pull request merged**
