### PR TITLE
Fixes #27663 - Make ansible var keys unique

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by lzap** [comment]
LGTM, can you rebase and get those tests passing? Many of them are failing.

**Comment by ares** [comment]
this seems as rex failures though (dependency of the plugin), I don't think it would be related to this PR

**Comment by xprazak2** [comment]
Test failures should be fixed with the new rex release: https://github.com/theforeman/foreman_remote_execution/commit/c8afb22415a82d84d116f22caabc080192542ee1

**Comment by ares** [comment]
[test foreman_ansible]

**Comment by ares** [comment]
There are still some REX issues, but unrelated to this patch. Tested it and it works, merging :+1:

**Pull request merged**
