### PR TITLE
Allow GH actions and drop travis

### PR DESCRIPTION
**Pull request by ezr-ondrej**
- Fix ability to run `rubocop` locally in the repository.
- Add GH actions tests
- Drop Travis tests

Example of run: https://github.com/ezr-ondrej/foreman_ansible/actions

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Hmm for some reason the REX feature is not in the database if the tests are being run through GH actions.
Any idea why @adamruzicka?

**Comment by adamruzicka** [comment]
I think that's the reason why I had to add `bundle exec rake db:test:prepare` when writing the gh action for leapp plugin https://github.com/theforeman/foreman_leapp/blob/master/.github/workflows/ruby.yml#L79 .

I think db:create creates development and test databases, migrate and seed prepare the development database. The when you run the tests, it clones the schema of the development database, but not the data inside it, so the db is completely blank. Or at least something along the lines of this

**Comment by ezr-ondrej** [comment]
Great, that did the trick https://github.com/ezr-ondrej/foreman_ansible/actions/runs/194710574!
Thanks @adamruzicka

**Comment by adamruzicka** [comment]
Could you rebase please?

**Comment by ezr-ondrej** [comment]
Done :+1:

**Comment by adamruzicka** [comment]
I think rubocop is unhappy about this, unless codeclimate uses a different config :shrug:

**Comment by ezr-ondrej** [comment]
Hm, I've just turned that cop down as there is not a lot of certainity about it https://github.com/rubocop-hq/rubocop-rails/issues/260

**Comment by ezr-ondrej** [comment]
I believe we are :green_heart: https://github.com/ezr-ondrej/foreman_ansible/actions (last two)

**Review by adamruzicka — APPROVED** [review]
ACK

**Comment by adamruzicka** [comment]
Thank you @ezr-ondrej !

**Pull request merged**
