### PR TITLE
Fixes #24694 - handle nil sources

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
updated to 2.3 (to be consistent with core)

**Comment by bastilian** [comment]
Should we maybe do the rubocop change in a separate PR, as it seems to trigger a lot of issues with codeclimate/rubocop, and only address the minor fixes that were before?

**Comment by ares** [comment]
yes, I'll open separate PR with it

**Comment by ares** [comment]
rebased, fingers crossed :-)

**Comment by ares** [comment]
oh there were new cops failing

**Comment by dLobatog** [comment]
@ares Looks green to me, 2 core integration tests failed but that's OK - https://ci.theforeman.org/job/foreman_ansible-pull-request/144/ , rubocop looks 100% clean here too https://ci.theforeman.org/job/foreman_ansible-pull-request/144/database=postgresql,label=fast,ruby=2.3/consoleFull

Merging!

**Comment by dLobatog** [comment]
@ares Looks green to me, 2 core integration tests failed but that's OK - https://ci.theforeman.org/job/foreman_ansible-pull-request/144/ , rubocop looks 100% clean here too https://ci.theforeman.org/job/foreman_ansible-pull-request/144/database=postgresql,label=fast,ruby=2.3/consoleFull

Merging!

**Pull request merged**
