### PR TITLE
Fixes #34094 - use report importer registry

### PR DESCRIPTION
**Pull request by lzap**
See https://github.com/theforeman/foreman/pull/8958#issuecomment-986732271

Do not merge until the core PR is in.

Also minimum foreman version will be 3.2 now, I cannot find this in `engine.rb`?

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
> Also minimum foreman version will be 3.2 now, I cannot find this in `engine.rb`?

It is in `lib/foreman_ansible/register.rb`

**Comment by ezr-ondrej** [comment]
Actually this would work without the core patch, wouldn't it? We call super there, so we should get the correct result with `Ansible` with bit of code order luck

**Comment by lzap** [comment]
Hmm tests are failing, any idea?

```
2021-12-10T11:37:26 [W|app|] Failed to register foreman-tasks plugin (PG::UndefinedTable: ERROR:  relation "foreman_tasks_recurring_logics" does not exist
 | LINE 8:  WHERE a.attrelid = '"foreman_tasks_recurring_logics"'::regc...
```

> Actually this would work without the core patch, wouldn't it? We call super there, so we should get the correct result with `Ansible` with bit of code order luck

Unsure, it is a clusterfuck implementation. If you say it will work and tests will pass then sure, let's do it!

**Comment by ezr-ondrej** [comment]
foreman_ansible tests are broken, we are on GH actions here for a while now and so far it works quite nicely

**Review by ezr-ondrej — APPROVED** [review]
Thanks @lzap ! :+1:

**Comment by ezr-ondrej** [comment]
CP 7.0: 84b32f0

**Pull request merged**
