### PR TITLE
fixes #17558 Add support to import junos facts in Foreman.

### LINKED ISSUE #20: Import ansible junos facts into Foreman
Would it be possible to catch the role Juniper.junos junos_get_facts then format for input into Foreman for a JunOS based device.

This would be really nice since Foreman can already support ZTP provisioning for JunOS devices.

Once the device was provisioned by Foreman, Ansible can be paired with Juniper.junos and NAPALM to manage configurations like pulling parameters from Foreman via foreman_ansible_inventory script. Foreman would then have complete lifecycle for JunOS.

https://github.com/Juniper/ansible-junos-stdlib/blob/master/library/junos_get_facts

https://github.com/theforeman/foreman_ansible_inventory

https://github.com/napalm-automation/napalm-ansible

Playbook:

[root@radaransible ansible]# cat add_junos_dev.yml 
--- # Get JunOS Facts
- hosts: junos
  user: root
  sudo: no
  connection: local
  gather_facts: no
  roles:
  - Juniper.junos
    tasks:
    - name: Check if NETCONF is Available
      wait_for: host={{ inventory_hostname }} port=830 timeout=5
  - name: Retrieve information from devices running Junos OS
    junos_get_facts:  
      host={{ inventory_hostname }}
      user=somename
      passwd=xxxxxxx
    register: junos
  - name: Print Info
    debug: msg="{{ junos.facts }}"
  - name: version
    debug: msg="{{ junos.facts.version }}"

Script Run:
# ansible-playbook add_junos_dev.yml -v

plugin foreman_callback.pyc: SSL verification of https://localhost:443 disabled

PLAY [junos] *****************************************************************\* 

TASK: [Check if NETCONF is Available] ****************************************\* 
ok: [s1casw.company.net] => {"changed": false, "elapsed": 0, "path": null, "port": 830, "search_regex": null, "state": "started"}

TASK: [Retrieve information from devices running Junos OS] *******************\* 
ok: [s1casw.company.net] => {"changed": false, "facts": {"HOME": "/var/home/somename", "RE0": {"last_reboot_reason": "0x2000:hypervisor reboot ", "mastership_state": "master", "model": "QFX Routing Engine", "status": "OK", "up_time": "71 days, 21 hours, 54 minutes, 5 seconds"}, "RE1": {"last_reboot_reason": "0x2000:hypervisor reboot ", "mastership_state": "backup", "model": "QFX Routing Engine", "status": "OK", "up_time": "71 days, 21 hours, 54 minutes, 17 seconds"}, "domain": "company.net", "fqdn": "S1CASw1.company.net", "has_2RE": true, "hostname": "S1CASw1", "ifd_style": "SWITCH", "master": "RE0", "model": "Virtual Chassis", "personality": "SWITCH", "serialnumber": "VF3333333333", "switch_style": "VLAN", "vc_capable": true, "vc_mode": "Enabled", "version": "14.1X53-D30.3", "version_RE0": "14.1X53-D30.3", "version_RE1": "14.1X53-D30.3", "version_info": {"build": 3, "major": [14, 1], "minor": [53, "D", 30], "type": "X"}}}

TASK: [Print Info] ***********************************************************\* 
ok: [s1casw.company.net] => {
    "msg": "{u'domain': u'company.net', u'serialnumber': u'VF3333333333', u'ifd_style': u'SWITCH', u'version_RE1': u'14.1X53-D30.3', u'version_info': {u'major': [14, 1], u'type': u'X', u'build': 3, u'minor': [53, u'D', 30]}, u'version_RE0': u'14.1X53-D30.3', u'RE0': {u'status': u'OK', u'last_reboot_reason': u'0x2000:hypervisor reboot ', u'model': u'QFX Routing Engine', u'up_time': u'71 days, 21 hours, 54 minutes, 5 seconds', u'mastership_state': u'master'}, u'RE1': {u'status': u'OK', u'last_reboot_reason': u'0x2000:hypervisor reboot ', u'model': u'QFX Routing Engine', u'up_time': u'71 days, 21 hours, 54 minutes, 17 seconds', u'mastership_state': u'backup'}, u'fqdn': u'S1CASw1.company.net', u'has_2RE': True, u'switch_style': u'VLAN', u'version': u'14.1X53-D30.3', u'master': u'RE0', u'hostname': u'S1CASw1', u'HOME': u'/var/home/somename', u'vc_mode': u'Enabled', u'model': u'Virtual Chassis', u'vc_capable': True, u'personality': u'SWITCH'}"
}

TASK: [version] **************************************************************\* 
ok: [s1casw.company.net] => {
    "msg": "14.1X53-D30.3"
}

PLAY RECAP *******************************************************************\* 
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
s1casw.company.net        : ok=4    changed=0    unreachable=0    failed=0 

Log Capture:

"POST /api/v2/hosts/facts" doesn't fire off when ansible "gather_facts: no" but "junos_get_facts" is run.

2016-03-20 20:37:45,333 requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): localhost
2016-03-20 20:37:45,511 requests.packages.urllib3.connectionpool "POST /api/v2/hosts/facts HTTP/1.1" 201 None

2016-03-20 19:13:29,617 p=5671 u=root |  /usr/bin/ansible-playbook add_junos_dev.yml -v
2016-03-20 19:13:29,617 p=5671 u=root |  
2016-03-20 19:13:30,353 p=5671 u=root |  PLAY [junos] *****************************************************************\* 
2016-03-20 19:13:30,355 p=5671 u=root |  TASK: [Check if NETCONF is Available] ****************************************\* 
Mar 20 19:13:30 radaransible ansible-wait_for: Invoked with host=s1casw.company.net connect_timeout=5 delay=0 state=started timeout=5 exclude_hosts=None search_regex=None path=None port=830
2016-03-20 19:13:30,607 p=5671 u=root |  ok: [s1casw.company.net] => {"changed": false, "elapsed": 0, "path": null, "port": 830, "search_regex": null, "state": "started"}
2016-03-20 19:13:30,608 p=5671 u=root |  TASK: [Retrieve information from devices running Junos OS] *******************\* 
Mar 20 19:13:30 radaransible ansible-junos_get_facts: Invoked with console=None passwd=xxxxxxxx host=s1casw.company.net savedir=None user=somename logfile=None port=830
2016-03-20 19:13:34,175 p=5671 u=root |  ok: [s1casw.company.net] => {"changed": false, "facts": {"HOME": "/var/home/somename", "RE0": {"last_reboot_reason": "0x2000:hypervisor reboot ", "mastership_state": "master", "model": "QFX Routing Engine", "status": "OK", "up_time": "71 days, 20 hours, 31 minutes, 33 seconds"}, "RE1": {"last_reboot_reason": "0x2000:hypervisor reboot ", "mastership_state": "backup", "model": "QFX Routing Engine", "status": "OK", "up_time": "71 days, 20 hours, 31 minutes, 46 seconds"}, "domain": "company.net", "fqdn": "S1CASw1.company.net", "has_2RE": true, "hostname": "S1CASw1", "ifd_style": "SWITCH", "master": "RE0", "model": "Virtual Chassis", "personality": "SWITCH", "serialnumber": "VF3333333333", "switch_style": "VLAN", "vc_capable": true, "vc_mode": "Enabled", "version": "14.1X53-D30.3", "version_RE0": "14.1X53-D30.3", "version_RE1": "14.1X53-D30.3", "version_info": {"build": 3, "major": [14, 1], "minor": [53, "D", 30], "type": "X"}}}
2016-03-20 19:13:34,176 p=5671 u=root |  TASK: [Print Info] ***********************************************************\* 
2016-03-20 19:13:34,206 p=5671 u=root |  ok: [s1casw.company.net] => {
    "msg": "{u'domain': u'company.net', u'serialnumber': u'VF3333333333', u'ifd_style': u'SWITCH', u'version_RE1': u'14.1X53-D30.3', u'version_info': {u'major': [14, 1], u'type': u'X', u'build': 3, u'minor': [53, u'D', 30]}, u'version_RE0': u'14.1X53-D30.3', u'RE0': {u'status': u'OK', u'last_reboot_reason': u'0x2000:hypervisor reboot ', u'model': u'QFX Routing Engine', u'up_time': u'71 days, 20 hours, 31 minutes, 33 seconds', u'mastership_state': u'master'}, u'RE1': {u'status': u'OK', u'last_reboot_reason': u'0x2000:hypervisor reboot ', u'model': u'QFX Routing Engine', u'up_time': u'71 days, 20 hours, 31 minutes, 46 seconds', u'mastership_state': u'backup'}, u'fqdn': u'S1CASw1.company.net', u'has_2RE': True, u'switch_style': u'VLAN', u'version': u'14.1X53-D30.3', u'master': u'RE0', u'hostname': u'S1CASw1', u'HOME': u'/var/home/somename', u'vc_mode': u'Enabled', u'model': u'Virtual Chassis', u'vc_capable': True, u'personality': u'SWITCH'}"
}
2016-03-20 19:13:34,207 p=5671 u=root |  TASK: [version] **************************************************************\* 
2016-03-20 19:13:34,212 p=5671 u=root |  ok: [s1casw.company.net] => {
    "msg": "14.1X53-D30.3"
}
2016-03-20 19:13:34,213 p=5671 u=root |  PLAY RECAP *******************************************************************\* 
2016-03-20 19:13:34,248 requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): localhost
2016-03-20 19:13:34,640 requests.packages.urllib3.connectionpool "POST /api/v2/reports HTTP/1.1" 201 None

### PR DESCRIPTION
**Pull request by ganeshnalawade**
Import junos facts into Foreman received from device by running
'junos_facts' or 'junos_get_facts' Ansible module.

As Ansible junos facts does not include ip address related
information it is not shown in Foreman.

### CODE REVIEW

**Comment by dLobatog** [comment]
@theforeman-bot ok to test 

If tests pass, I'll merge and then fix the codeclimate issues myself on a separate PR. It'd be really nice to make a release out of this & yesterdays #60 

@ganeshnalawade Curious, are you currently using Foreman with JunOS somewhere in RedHat? I'd like to have a chat to learn a bit about that topic if you have the time. Particularly I'd want to know how your use case looks like, how you're testing it, etc.. Great patch overall, thanks 😄

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
Thanks @ganeshnalawade

**Comment by ganeshnalawade** [comment]
@dLobatog Sure, will ping you on irc soon. Thank you

**Pull request merged**
