### PR TITLE
Fixes #33877 - Improve styling for roles tab

### PR DESCRIPTION
**Pull request by xprazak2**
Before: 
roles-before

After:
roles-after

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
The position on the bottom is little bit awekward, I'd keep the button above the table.
@ares opinions?

**Comment by ares** [comment]
yeah, neither button position is clearly better, let's revert that to the top, but thanks for testing!

**Comment by ezr-ondrej** [comment]
I still like the sentence change and movement of the "all roles" link afther the header not next of the button.

**Comment by xprazak2** [comment]
Now:

roles-btn

**Review by ezr-ondrej — APPROVED** [review]
:+1: on that, ~we just have some snapshots failures I guess~ EDIT: I've seen old test status

**Pull request merged**
