### PR TITLE
Fixes #27984 - Provide an option to run a job with playbook as input

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by xprazak2** [comment]
Works for me, but there is a lot of test failures. It seems like newer rex is needed.

**Comment by adamruzicka** [comment]
Let's see if [test foreman_ansible] helps

**Comment by ares** [comment]
does not seem to help

**Comment by mmoll** [comment]
please rebase

**Comment by adamruzicka** [comment]
I rebased it yesterday, it is based on dd17c402aaa72268bbcb0a637cf9b30f35dd5281 and I'm sure it is pushed here. Not sure what is going on

**Comment by mmoll** [comment]
[test foreman_ansible]

**Comment by mmoll** [comment]
Right, the chromedriver thing was in core.

**Comment by mmoll** [comment]
pgsql green. :green_heart:

**Pull request merged**
