### PR TITLE
#18731 - Ansible Run fails with internal error

### PR DESCRIPTION
**Pull request by chilicat**
Ansible Run fails with internal error "Runner error: ArgumentError - comparison of String with 0 failed"

### CODE REVIEW

**Comment by chilicat** [comment]
Satisfy codeclimate style guide

**Comment by chilicat** [comment]
@dLobatog ping

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
👍 if tests pass

**Comment by dLobatog** [comment]
Thanks @chilicat !

**Comment by chilicat** [comment]
thank you for merging

**Pull request merged**
