### PR TITLE
Fixes #32189 - Improve ansible config report data

### PR DESCRIPTION
**Pull request by yifatmakias**
Add textual representation of the ansible task based on data provided by the module, if there's no human readable string, add the message "no data available" information.

### CODE REVIEW

**Review by ares — CHANGES_REQUESTED** [review]
I have created a role, that creates a bit meaningful report, I'd recommend using that for further improving the report output. 
https://github.com/ares/foreman_ansible_test

I tried to apply this PR and have few immediate comments for this PR. The 
report

1) The module column now seems to be in the Task name, I'd drop that one completely (sorry I know I told you it may be interesting, but I didn't see it in real world)

2) I'd rename Task name to Task now.

I think we should change the content of the Message column entirely, but that's a different PR

**Comment by yifatmakias** [comment]
this PR depends on another PR:
https://github.com/theforeman/foreman-ansible-modules/pull/1232

**Comment by xprazak2** [comment]
The task messages look nice:

report-output

**Comment by xprazak2** [comment]
@ares, any additional suggestions for improvements?

**Comment by ares** [comment]
This looks awesome! Long term, I think we should move this logic to the callback itself, so we avoid storing huge JSONs in our DB. That causes problems on a big setups. However for now it's good we can tweak the report messages while we still have all data. So :+1: from me, good job.

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
