### PR TITLE
Fixes #26431 - ship inventory role by default

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by xprazak2** [comment]
Adds the role for me, rubocop offences related.

**Comment by ares** [comment]
Thanks, rubocop should be now fixed

**Comment by xprazak2** [comment]
I can see:
```
** Invoke foreman_ansible:rubocop (first_time)
** Execute foreman_ansible:rubocop
** Invoke rubocop_foreman_ansible (first_time)
** Execute rubocop_foreman_ansible
RuboCop failed!
Running RuboCop...
Inspecting 105 files
...........................................................C.............................................

Offenses:

/home/jenkins/workspace/foreman_ansible-pull-request/database/postgresql/label/fast/ruby/2.4/plugin/lib/foreman_ansible/register.rb:74:5: C: Layout/AlignParameters: Align the parameters of a method call if they span more than one line.
    [:view_hosts, :view_hostgroups, :view_facts],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/jenkins/workspace/foreman_ansible-pull-request/database/postgresql/label/fast/ruby/2.4/plugin/lib/foreman_ansible/register.rb:75:5: C: Layout/AlignParameters: Align the parameters of a method call if they span more than one line.
    'Permissions required for the user which is used by Ansible Tower Dynamic Inventory Item'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

105 files inspected, 2 offenses detected
```

**Comment by ares** [comment]
Yeah sorry, I hope I got it right this time

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
