### PR TITLE
Fixes #34190 - consume pagination from core

### PR DESCRIPTION
**Pull request by amirfefer**
needs https://github.com/theforeman/foreman/pull/8990

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
The core PR is in, I'll rebase this to see what happens with tests

**Comment by amirfefer** [comment]
@ezr-ondrej, rebased 🙏

**Comment by amirfefer** [comment]
@ezr-ondrej, js tests are 🟢

**Comment by ezr-ondrej** [comment]
Ruby failures unrelated.

**Review by ezr-ondrej — APPROVED** [review]
The core PR is in, lets get this in as well. Thanks @amirfefer ! :+1:

**Pull request merged**
