### PR TITLE
Fixes #26093 - restore searching by role

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
the issue is only reproducible with katello, which adds "role" for searching by system purpose

**Comment by xprazak2** [comment]
Fixes the issue for me, test failures unrelated, should be fixed in #247

**Comment by ares** [comment]
[test foreman_ansible] should be green now

**Comment by xprazak2** [comment]
Maybe rebase on top of master with the fix for missing permissions will help.

**Comment by ares** [comment]
yeah, just rebased

**Comment by xprazak2** [comment]
The only failing test is AuditExtensions, I do not think it is related.

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
