### PR TITLE
Test with NodeJS 18

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Could be related:
```
Error:
HostgroupJsTest#test_0001_hostgroup without roles should have disabled links:
ActionController::RoutingError: No route matches [GET] "/webpack/foreman-vendor.css"
    lib/foreman/middleware/logging_context_request.rb:11:in `call'

Error:
HostgroupJsTest#test_0002_hostgroup with roles should have clickable links:
ActionController::RoutingError: No route matches [GET] "/webpack/foreman-vendor.css"
    lib/foreman/middleware/logging_context_request.rb:11:in `call'
```

**Comment by ekohl** [comment]
With https://github.com/theforeman/foreman/pull/10045 merged I'd expect this to pass so I've pushed an update to restart the tests.

**Comment by ekohl** [comment]
Oh, @MariaAga's branch doesn't contain the fix. @MariaAga can you rebase your NodeJS 18 commit on Foreman develop?

**Comment by MariaAga** [comment]
> rebase your NodeJS 18 commit on Foreman develop?

Done

**Comment by ekohl** [comment]
This is green (except for the Redmine issues test), so that's great.

**Pull request closed without merging**
