### PR TITLE
Fixes #33980 - backport the RHEL OS parsing

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
This is a CP of https://github.com/theforeman/foreman/pull/8943 for the older versions, I didn't bring back the tests since we don't have the infra here for the static fixtures. If tests are green in core, it's unlikely the code wouldn't work here.

**Review by adamruzicka — APPROVED** [review]
Looks good, let's get this in

**Comment by ezr-ondrej** [comment]
I guess we are pulling in the new smart_proxy_dynflow, which we should not have (that's why the tests fail).
That got me thinking, won't this happen on debian @adamruzicka?

**Review by ezr-ondrej — APPROVED** [review]
Last comment has nothing to do with this PR, it is fine to get in :+1:

**Comment by adamruzicka** [comment]
> won't this happen on debian?

Newer smart_proxy_dynflow should not be available in debian repos IIRC

**Pull request merged**
