### PR TITLE
Fixes #32031 - proxy batch size for Ansible

### PR DESCRIPTION
**Pull request by ezr-ondrej**
This follows REX#32032 and uses it to tweak batch sizes for Ansible.

- [ ] Needs  https://github.com/theforeman/foreman_remote_execution/pull/566 and bump REX dependency accordingly.

### CODE REVIEW

**Comment by adamruzicka** [comment]
This should now be unblocked and needs a rebase

**Comment by ezr-ondrej** [comment]
Thanks, rebased.

**Comment by xprazak2** [comment]
What is the status here?

**Review by ares — APPROVED** [review]
Thanks @ezr-ondrej, merging!

**Pull request merged**
