### PR TITLE
Fixes #37451 - Support Zeitwerk loader

### PR DESCRIPTION
**Pull request by ofedoren**
~WIP~

requires https://github.com/theforeman/foreman-tasks/pull/752

### CODE REVIEW

**Comment by ekohl** [comment]
@ofedoren https://github.com/theforeman/foreman_ansible/pull/724 contains another fix. Are you aware of that and can we converge on a single PR?

**Comment by ofedoren** [comment]
@ekohl, yeap, I'm aware, but it's easier for me to update this PR if I find something to address during local testing.

That PR differs in this https://github.com/theforeman/foreman_ansible/pull/724/commits/0ad16b69acd7df74b6de25f12112e9b8b290b668, which is simply another way of dealing with a file not being named as the constant it defines.

**Comment by ofedoren** [comment]
Ready to merge after https://github.com/theforeman/foreman/pull/10131 is merged, dropped the commit for testing with Foreman PR, the latest run was green (look test:foreman_ansible which was on Ruby 3 and Node 14, I think this plugin sometimes gives false-positives):
Screenshot_20240903_143351

**Review by adamruzicka — CHANGES_REQUESTED** [review]
We'll need to update the gemspec to allow tasks >= 10.0.0

**Comment by adamruzicka** [comment]
And also rex >= 14.0.0

**Comment by ekohl** [comment]
Any idea why it's failing now?

**Comment by adamruzicka** [comment]
Sigh, long live flaky tests. Packit is red, changes in packaging will be needed to make them green.

**Comment by adamruzicka** [comment]
Thank you @ofedoren !

**Pull request merged**
