### PR TITLE
Fixes #33841 - Add pagination to variable overrides

### PR DESCRIPTION
**Pull request by xprazak2**
Needs https://github.com/theforeman/foreman_ansible/pull/473

### CODE REVIEW

**Comment by xprazak2** [comment]
No longer wip.

**Review by amirfefer — APPROVED** [review]
Thanks, @xprazak2 👍  
Tested and works as expected,  same issue as #480, the skeleton loading affects the entire tab's content, but will be fixed later

**Comment by ezr-ondrej** [comment]
This needs rebase now. but should be straight forward and it's ready to merge right after that :+1:

**Review by amirfefer — COMMENTED** [review]
@xprazak2, a rebase is needed

**Comment by ezr-ondrej** [comment]
[test foreman_ansible]

**Comment by xprazak2** [comment]
All green now.

**Comment by ezr-ondrej** [comment]
Thanks @xprazak2 ! :+1:

**Pull request merged**
