### PR TITLE
Fixes #17702 - Make ansible run cancelable

### PR DESCRIPTION
**Pull request by chilicat**
Make ansible task cancelable by killing the ansible process.

### CODE REVIEW

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@chilicat This doesn't do much by itself. I don't have anything against this code but it'll be dead code if nothing uses it. You'd have to add functionality to call this from either the proxy or Foreman for it to work. Were you missing some extra files in the commit or something similar?

Thanks for the contribution!

**Comment by chilicat** [comment]
In my testing the cancel button in the task view was not able cancel the running ansible task. By adding this simple lines everything works as expected. 

Why do you think it is dead code?

**Comment by chilicat** [comment]
Kill can be overwritten:
https://github.com/theforeman/foreman-tasks/blob/5b9507dd42bb98976344e2adaf5f2c1c87c2df71/lib/foreman_tasks_core/runner/base.rb#L36

**Comment by chilicat** [comment]
I have improved the implementation. The task has behaved different in a development environment, it was not enough to just kill the process.

**Comment by dLobatog** [comment]
[test] - @chilicat I was dumb enough not to look into foreman-tasks-core. Will merge if tests pass 😄 thanks again

**Comment by dLobatog** [comment]
Thanks @chilicat !

**Comment by chilicat** [comment]
Thank you for the effort reviewing and commenting.
Happy holidays.

**Pull request merged**
