### PR TITLE
Fixes #22586 - backport patch from smart_proxy_ansible

### PR DESCRIPTION
**Pull request by ares**
bringing this to the right location, foreman_ansible_core was dropped in that repo, the patch never made it to released version

https://github.com/theforeman/smart_proxy_ansible/pull/11

### CODE REVIEW

**Comment by ares** [comment]
@xprazak2 could you please take a look?

**Comment by xprazak2** [comment]
[test]

**Comment by xprazak2** [comment]
:+1:

**Comment by ares** [comment]
Thanks @xprazak2, merging then.

**Pull request merged**
