### PR TITLE
Host detail - role's variables

### PR DESCRIPTION
**Pull request by stejskalleos**
Display number of variables for each role with link
to the role variables index page with pre-set filter.

### CODE REVIEW

**Comment by stejskalleos** [comment]
@ezr-ondrej I give up, no idea how to fix the issue.

**Comment by ezr-ondrej** [comment]
The PR got merged and this should be unblocked and can be implemented ^_^

**Comment by ezr-ondrej** [comment]
JS failure says: `Could not locate module foremanReact/components/Pagination/PaginationWrapper` did you rebased on new master?

**Comment by stejskalleos** [comment]
Yop I did, branch is on latest `master`

**Comment by ezr-ondrej** [comment]
Right, just a lefover and the component was just removed from core.
#527

**Comment by ezr-ondrej** [comment]
So rebase should fix the tests now, right?

**Comment by stejskalleos** [comment]
I fixed following tests:
```
AnsibleHostDetail/components/RolesTab/__test__/EditRoles.test.js
AnsibleHostDetail/components/RolesTab/__test__/RolesTab.test.js
```

On my local dev setup, these tests are failing on `master` too:
```
webpack/components/AnsibleHostDetail/components/AnsibleHostInventory/AnsibleHostInventory.test.js
webpack/routes/HostgroupJobs/__test__/HostgroupJobs.test.js
webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.test.js
```

**Comment by stejskalleos** [comment]
@ezr-ondrej Looks like tests are green, for some reason some of them are failing on my local dev setup, but that's a story for another time ...

**Review by ezr-ondrej — APPROVED** [review]
Thanks @stejskalleos ! :+1:

**Pull request merged**
