### PR TITLE
Refs #30398 - fix rubocop

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Don't we want to change the rule instead?
The :rocket: style is making me sad :panda_face: and core is accepting both already.

**Comment by ares** [comment]
@adamruzicka opinions? I don't care that much and I'm all for keeping pandas happy :-)

**Comment by adamruzicka** [comment]
I used to heavily favor rockets, but not so much nowadays. How about sticking with core and allowing both?

**Comment by ezr-ondrej** [comment]
I'd be for allowing both :+1:
What about [no_mixed_keys](https://www.rubydoc.info/gems/rubocop/0.46.0/RuboCop/Cop/Style/HashSyntax)?

**Comment by ezr-ondrej** [comment]
Thank you @ares ! I've opened #356 to change the required Hash style according to the discussion.

**Pull request closed without merging**
