### PR TITLE
Fixes #26881 - use dynamic attrs for Factory Bot 5.x compat

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
test failures unrelated, AFAICT

**Comment by tbrisker** [comment]
[test foreman_ansible]

**Comment by tbrisker** [comment]
tests are now failing due to https://github.com/peerigon/parse-domain/issues/72

**Comment by tbrisker** [comment]
[test foreman_ansible]

**Comment by tbrisker** [comment]
rex tests are now failing here:
```
/usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/definition_proxy.rb:97:in `method_missing': undefined method 'template' in 'job_template' factory (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/foreman_remote_execution-1.8.0/test/factories/foreman_remote_execution_factories.rb:5:in `block (2 levels) in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/syntax/default.rb:18:in `instance_eval'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/syntax/default.rb:18:in `factory'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/foreman_remote_execution-1.8.0/test/factories/foreman_remote_execution_factories.rb:2:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/syntax/default.rb:49:in `instance_eval'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/syntax/default.rb:49:in `run'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/syntax/default.rb:7:in `define'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/foreman_remote_execution-1.8.0/test/factories/foreman_remote_execution_factories.rb:1:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/find_definitions.rb:20:in `block (2 levels) in find_definitions'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/find_definitions.rb:19:in `each'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/find_definitions.rb:19:in `block in find_definitions'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/find_definitions.rb:15:in `each'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/find_definitions.rb:15:in `find_definitions'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/factory_bot-5.0.2/lib/factory_bot/reload.rb:6:in `reload'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/foreman_remote_execution-1.8.0/test/test_plugin_helper.rb:9:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/foreman_remote_execution-1.8.0/test/functional/api/v2/foreign_input_sets_controller_test.rb:1:in `require'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/foreman_remote_execution-1.8.0/test/functional/api/v2/foreign_input_sets_controller_test.rb:1:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:17:in `require'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:5:in `select'
	from /usr/local/rvm/gems/ruby-2.5.1@foreman_ansible-pull-request-1/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:5:in `<main>'

**Comment by mmoll** [comment]
Hm, that because rex tests are also running implicitly(?) here... So to get this green with the current mechanics, a new rex release would be required.

**Comment by mmoll** [comment]
and maybe even a new -tasks release.

**Comment by mmoll** [comment]
[test foreman_ansible]

**Comment by mmoll** [comment]
[test foreman_ansible]

**Comment by mmoll** [comment]
test failures unrelated, AFAICT

**Comment by ares** [comment]
Thanks @mmoll, merging!

**Pull request merged**
