### PR TITLE
Fixes #33827 - Check permissions when changing overrides

### PR DESCRIPTION
**Pull request by xprazak2**
Needs https://github.com/theforeman/foreman_ansible/pull/473

### CODE REVIEW

**Comment by xprazak2** [comment]
Should be ready.

**Comment by ezr-ondrej** [comment]
It has JS failures and now a conflict as well

**Comment by xprazak2** [comment]
Rebased.

**Comment by ezr-ondrej** [comment]
This also enables delete, but server refuses to delete.
It is still step forward, so I'm going to merge, but it would be nice if we could fix the delete.

**Pull request merged**
