### PR TITLE
Fixes #33843 - improve the convert2rhel user experience

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Review by adamruzicka — COMMENTED** [review]
I don't have a katello dev env or new enough katello production-like deployment to properly test this, but code wise looks good.

**Comment by ares** [comment]
@stejskalleos do you have a setup to test? I know about one issue in REX re previewing such inputs, but that's unrelated to this PR. The patch is already applied on demo hw, if that convinces you @adamruzicka :-)

**Comment by stejskalleos** [comment]
@ares @adamruzicka  I have working setup with Katello, I will look at it

**Comment by stejskalleos** [comment]
@ares testing is blocked by https://github.com/theforeman/foreman/pull/8900

**Comment by stejskalleos** [comment]
:heavy_check_mark: LGTM

Command correctly generated with activation key's name:
```
convert2rhel -y --activationkey "convert2rhel_centos7" --org "Demo" > /root/convert2rhel.log
```

**Comment by ares** [comment]
note the demo hw had a slightly older version of the template without `--keep-rhsm` and with  the stdout redirection :-) ok since this is now confirmed, could it go in @adamruzicka ?

**Review by adamruzicka — APPROVED** [review]

**Comment by adamruzicka** [comment]
Thank you @ares & @stejskalleos !

**Pull request merged**
