### PR TITLE
 Fixes #23047 - PUT instead of POST for import/obsolete API endpoints

### PR DESCRIPTION
**Pull request by ofedoren**
It comes with another commit to avoid any merge conflicts for testing this PR.

### CODE REVIEW

**Comment by ares** [comment]
:+1: both are listed as put in config/routes.rb https://github.com/theforeman/foreman_ansible/blob/master/config/routes.rb#L56-L57

I guess @dLobatog / @bastilian you can either merge this instead of https://github.com/theforeman/foreman_ansible/pull/151 or merge that one first and this will need to be rebased

**Comment by ares** [comment]
[test]

**Comment by bastilian** [comment]
@ofedoren would you mind adding a test for each of these updated routes to `ansible_roles_controller_test`? Simply verifying the endpoints work and stub `.import!` on importer to return as it's functionality is tested in it's tests.

**Comment by ofedoren** [comment]
@bastilian , sure. But I'd rather wait https://github.com/theforeman/foreman_ansible/pull/154 to be merged, so I don't need to rewrite tests.

**Comment by ofedoren** [comment]
@bastilian updated. Sorry if I didn't get it right, but ```api_roles_importer_test``` already has tests for importer, doesn't it?

**Comment by ares** [comment]
tests were added, merging, thanks @ofedoren and @bastilian

**Pull request merged**
