### PR TITLE
Fixes #28042 - remove ansible-playbook option

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Comment by mmoll** [comment]
misses the last rubocop fix from master :robot:

**Comment by mmoll** [comment]
sqlite error unrelated :green_heart:

**Comment by xprazak2** [comment]
LGTM

**Comment by adamruzicka** [comment]
Shouldn't `ForemanAnsibleCore::Runner::Playbook` be removed as part of this too?

**Comment by ezr-ondrej** [comment]
> Shouldn't `ForemanAnsibleCore::Runner::Playbook` be removed as part of this too?

I intended to keep it for a one more version, but I will do it as a followup.

**Comment by ares** [comment]
Thanks everyone, merging!

**Pull request merged**
