### PR TITLE
Fixes #35190 - added ansible actions to hostgroups actions array

### PR DESCRIPTION
**Pull request by nofaralfasi**
Added ansible action to the actions' dropdown on the Hostgroups page without overriding the existing ones.

### CODE REVIEW

**Review by Ron-Lavi — APPROVED** [review]
Looks simple from the side of plugins :D
great work @nofaralfasi !

**Comment by Ron-Lavi** [comment]
meanwhile, it's blocked by https://github.com/theforeman/foreman/pull/9297

**Comment by Ron-Lavi** [comment]
tested with the Foreman PR and it works great, thanks @nofaralfasi !

**Comment by Ron-Lavi** [comment]
https://github.com/theforeman/foreman/pull/9297 got merged, triggering the failing tests to run.

**Comment by Ron-Lavi** [comment]
HostgroupExtensionsTest fails, probably related @nofaralfasi ?

**Comment by nofaralfasi** [comment]
@stejskalleos is there anything we could do regarding the failing tests?

**Comment by stejskalleos** [comment]
> @stejskalleos is there anything we could do regarding the failing tests?

Yop, https://github.com/theforeman/foreman_ansible/pull/548

**Comment by Ron-Lavi** [comment]
could you rebase @nofaralfasi ?

**Review by Ron-Lavi — APPROVED** [review]
It extends well :) LGTM 👍🏼

**Comment by ares** [comment]
Given this requires some Foreman core functionality, it should have probably bumped the minimal Foreman version to 3.4 at https://github.com/theforeman/foreman_ansible/blob/master/lib/foreman_ansible/register.rb#L4 and should have bumped the major version to 9.0. Perhaps it should be added as a separate commit.

**Comment by nofaralfasi** [comment]
> Given this requires some Foreman core functionality, it should have probably bumped the minimal Foreman version to 3.4 at https://github.com/theforeman/foreman_ansible/blob/master/lib/foreman_ansible/register.rb#L4 and should have bumped the major version to 9.0. Perhaps it should be added as a separate commit.

Thank you @ares for noticing. I created this [PR](https://github.com/theforeman/foreman_ansible/pull/552) with the required changes.

**Pull request merged**
