### PR TITLE
Fixes #27816 - setting initialization improvement

### PR DESCRIPTION
**Pull request by ezr-ondrej**
As theforeman/foreman#6902 got merge, we should merge this, to avoid double initialization.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test foreman_ansible]

**Comment by lzap** [comment]
There are failures :-(

**Comment by mmoll** [comment]
please rebase

**Comment by mmoll** [comment]
misses the last rubocop fix from master :robot:

**Comment by ezr-ondrej** [comment]
Right, let's see what about now :)

**Comment by adamruzicka** [comment]
postgres is green

**Comment by ares** [comment]
sorry, this needs rebasing, happy to merge right after

**Comment by adamruzicka** [comment]
:policeman:  is unhappy

**Comment by ezr-ondrej** [comment]
> :policeman: is unhappy

Someone have told him about my hidden stash :disappointed:
Rebased.

**Comment by ares** [comment]
Thanks @ezr-ondrej, merging!

**Pull request merged**
