### PR TITLE
Fixes #27389 - fix eslint

### PR DESCRIPTION
**Pull request by sharvit**

### CODE REVIEW

**Comment by sharvit** [comment]
btw, now travis will fail PR that break linting rules.

**Comment by ares** [comment]
Does this now require Foreman 1.23? If so, we need to bump major version here. (note for myself, we'll need to branch 3.0-stable

**Comment by ares** [comment]
if the answer is yes, please bump https://github.com/theforeman/foreman_ansible/blob/master/lib/foreman_ansible/version.rb

**Comment by sharvit** [comment]
@ares this change only affect the development environment

**Comment by ares** [comment]
> @ares this change only affect the development environment

@sharvit isn't https://github.com/theforeman/foreman_ansible/pull/289/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R12 actually changing the dependency? I suppose it only formalizes the requirement, but I'm rather cautious. I suppose the jquery is consumed from the core, so just checking whether this would still work if we rebuild against older version of Foreman.

**Comment by sharvit** [comment]
> > @ares this change only affect the development environment
> 
> @sharvit isn't https://github.com/theforeman/foreman_ansible/pull/289/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R12 actually changing the dependency? I suppose it only formalizes the requirement, but I'm rather cautious. I suppose the jquery is consumed from the core, so just checking whether this would still work if we rebuild against older version of Foreman.

As you assumed, it only formalizes the requirement to satisfy eslint. In any case the actual version will be supplied by foreman-core or by [@theforeman/vendor](https://github.com/theforeman/foreman-js/tree/master/packages/vendor) since `1.23`.

This will only affect your dev/test/storybook env where `jquery` wasn't available for you.

**Comment by sharvit** [comment]
Rebased.
Can we merge it?

**Comment by sharvit** [comment]
Can we merge it please?

**Comment by sharvit** [comment]
@tbrisker any chace helping reviewing/merging this PR?

**Comment by tbrisker** [comment]
[test foreman_ansible]

**Comment by ares** [comment]
I'm sorry for the delay, merging now, thanks @sharvit

**Pull request merged**
